/*
 * Copyright (c) 2023 Quoppo LLC
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_SHADOW_PB_H_INCLUDED
#define PB_SHADOW_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Shadow {
    int32_t red;
    int32_t green;
    int32_t blue;
    bool on;
} Shadow;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Shadow_init_default                      {0, 0, 0, 0}
#define Shadow_init_zero                         {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Shadow_red_tag                           1
#define Shadow_green_tag                         2
#define Shadow_blue_tag                          3
#define Shadow_on_tag                            4

/* Struct field encoding specification for nanopb */
#define Shadow_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    red,               1) \
X(a, STATIC,   SINGULAR, INT32,    green,             2) \
X(a, STATIC,   SINGULAR, INT32,    blue,              3) \
X(a, STATIC,   SINGULAR, BOOL,     on,                4)
#define Shadow_CALLBACK NULL
#define Shadow_DEFAULT NULL

extern const pb_msgdesc_t Shadow_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Shadow_fields &Shadow_msg

/* Maximum encoded size of messages (where known) */
#define Shadow_size                              35

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
